// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxBDnoQROFDoXY_73T2gG3PQoCdesHG-g',
    appId: '1:433301837855:web:f57aba287655274f6bdd2a',
    messagingSenderId: '433301837855',
    projectId: 'wanderlustapp-4cfc5',
    authDomain: 'wanderlustapp-4cfc5.firebaseapp.com',
    storageBucket: 'wanderlustapp-4cfc5.appspot.com',
    measurementId: 'G-8GX7ED8BBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjz2DCYmyNOlixITqlsbWtYjVp3Z1RDnw',
    appId: '1:433301837855:android:ce872c46c1eaaca26bdd2a',
    messagingSenderId: '433301837855',
    projectId: 'wanderlustapp-4cfc5',
    storageBucket: 'wanderlustapp-4cfc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsxd5-KAAq9LmUUwm8yocFPhqH7IJYzWM',
    appId: '1:433301837855:ios:ea6ee5777744e78b6bdd2a',
    messagingSenderId: '433301837855',
    projectId: 'wanderlustapp-4cfc5',
    storageBucket: 'wanderlustapp-4cfc5.appspot.com',
    iosBundleId: 'com.example.wanderlustapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsxd5-KAAq9LmUUwm8yocFPhqH7IJYzWM',
    appId: '1:433301837855:ios:a5db9ef61c0d38df6bdd2a',
    messagingSenderId: '433301837855',
    projectId: 'wanderlustapp-4cfc5',
    storageBucket: 'wanderlustapp-4cfc5.appspot.com',
    iosBundleId: 'com.example.wanderlustapp.RunnerTests',
  );
}
